version: "3"

services:
  # 前端服务
  ve-blog-element:
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    image: sparkinai-admin:latest  # 设置新的镜像名称和标签
    container_name: sparkinai-admin
    restart: always
    ports:
      - "19521:80"
